-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 10:42:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatPHP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatPHP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatPHP` DEFAULT CHARACTER SET utf8 ;
USE `chatPHP` ;

-- -----------------------------------------------------
-- Table `chatPHP`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatPHP`.`users` (
  `idusers` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatPHP`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatPHP`.`messages` (
  `idmessages` INT NOT NULL,
  `content` VARCHAR(1063) NULL,
  `date` DATETIME NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idmessages`),
  INDEX `fk_messages_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `chatPHP`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
